pyside6-uic mainwindow.ui -o ui_mainwindow.py
pyside6-uic output.ui -o ui_output.py
pyside6-uic feiteng_custom.ui -o ui_feiteng_custom.py
pyside6-uic feiteng_single.ui -o ui_feiteng_single.py
pyside6-uic feiteng_linggui_custom.ui -o ui_feiteng_linggui_custom.py
pyside6-uic feiteng_linggui_display.ui -o ui_feiteng_linggui_display.py
pyside6-uic page.ui -o ui_page.py
pyside6-uic page_NaJia.ui -o ui_page_NaJia.py
pyside6-uic page_NaZi.ui -o ui_page_NaZi.py
pyside6-uic linggui_custom.ui -o ui_linggui_custom.py
pyside6-uic linggui_single.ui -o ui_linggui_single.py
pyside6-uic najia_nazi_time_acupoint.ui -o ui_najia_nazi_time_acupoint.py
pyside6-uic feiteng_linggui_time_acupoint.ui -o ui_feiteng_linggui_time_acupoint.py
pyside6-uic najia_nazi_display.ui -o ui_najia_nazi_display.py